# Generated by Django 3.1.4 on 2021-01-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_serving_times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Serving_Time_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('restaurant_serving_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_serving_times.restaurant_serving_times')),
            ],
            options={
                'verbose_name_plural': '3-1 Restaurant_Serving_Time_Categories',
            },
        ),
    ]
