# Generated by Django 3.1.4 on 2021-01-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_serving_time_categories',
            name='restaurant_serving_time_category_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
