# Generated by Django 3.1.4 on 2021-01-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=50, unique=True)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=70)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('bank_card_type', models.CharField(choices=[('debit_card', 'debit card'), ('credit_card', 'credit card')], default='debit card', max_length=15)),
                ('bank_card_number', models.CharField(max_length=30)),
                ('bank_expiry_year', models.IntegerField(default='25')),
                ('bank_expiry_month', models.IntegerField(default='01')),
                ('bank_security_code', models.CharField(max_length=10)),
                ('bank_card_holder_name', models.CharField(max_length=30)),
                ('number_of_tables', models.IntegerField()),
                ('restaurant_menu_link', models.URLField(blank=True, max_length=50)),
                ('restaurant_account_username', models.EmailField(max_length=50)),
                ('restaurant_account_password', models.CharField(default='', max_length=15)),
                ('chef_waiter_account_username', models.EmailField(max_length=50)),
                ('chef_waiter_account_password', models.CharField(default='', max_length=15)),
                ('opening_time_hour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='9', max_length=2)),
                ('opening_time_minutes', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='30', max_length=2)),
                ('closing_time_hour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='20', max_length=2)),
                ('closing_time_minutes', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2)),
            ],
            options={
                'verbose_name_plural': '1 Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_QR_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.FileField(default='-', upload_to='restaurant_qr_codes/')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name_plural': '1-2 Restaurant ID QR codes',
            },
        ),
        migrations.CreateModel(
            name='Restaurant_PDF_Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_menu', models.FileField(upload_to='restaurant_pdf_menus/')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name_plural': '1-1 Restaurant PDF Menus',
            },
        ),
    ]
