# Generated by Django 3.1.4 on 2021-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_category_dishes', '0003_auto_20210107_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_serving_time_category_dishes',
            name='dish_photo',
            field=models.FileField(default='-', upload_to='meal_photos/'),
        ),
    ]
