# Generated by Django 3.1.4 on 2021-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_category_dishes', '0004_restaurant_serving_time_category_dishes_dish_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_serving_time_category_dishes',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant_serving_time_category_dishes',
            name='dish_id',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
