# Generated by Django 3.1.4 on 2021-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_category_dishes', '0006_auto_20210113_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_serving_time_category_dishes',
            name='dish_brief_descriptions',
            field=models.CharField(max_length=25),
        ),
    ]
