# Generated by Django 3.1.4 on 2021-03-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_category_dishes', '0008_auto_20210312_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_serving_time_category_dishes',
            name='dish_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
