# Generated by Django 3.1.4 on 2021-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_serving_time_category_dishes', '0010_auto_20210312_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_serving_time_category_dishes',
            name='dish_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
